import { SUCCESS_MESSAGE, ERROR_MESSAGE } from './message'
import { SET_SPORT, REMOVE_SPORT } from './sport'
import { SET_USER, REMOVE_USER } from './user'
import { SET_PAGE_PATH } from './pagePath'

const GET_PROVIDERLEAGUE_DATA = 'GET_PROVIDERLEAGUE_DATA';
const SET_PROVIDERLEAGUE_DATA = 'SET_PROVIDERLEAGUE_DATA';

export  {
    GET_PROVIDERLEAGUE_DATA, SET_PROVIDERLEAGUE_DATA,
    SUCCESS_MESSAGE, ERROR_MESSAGE, SET_USER, REMOVE_USER, SET_PAGE_PATH, SET_SPORT, REMOVE_SPORT
}